name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v13
    - uses: coursier/cache-action@v6
    - run: sbt clean coverage test coverageReport
    - run: bash <(curl -s https://codecov.io/bash)