name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v2
    - uses: coursier/cache-action@v3
    - run: csbt clean coverage test coverageReport
    - run: bash <(curl -s https://codecov.io/bash)